### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by Nextovoy** [mathe00/obsidian-better-auto-linker-plugin#1]
I installed the plugin, but I didn't notice any new features - how does it work?

Could you provide a demo video or screenshots with a description?
In other words, I need instructions on how to use the plugin.

**Comment by mathe00** [comment]
> I installed the plugin, but I didn't notice any new features - how does it work?
> 
> Could you provide a demo video or screenshots with a description? In other words, I need instructions on how to use the plugin.

Hi @Nextovoy,

Thank you for your interest in the plugin! I should mention that this was primarily a personal side project that I'm no longer actively maintaining.

Instead, I'd recommend checking out these alternatives:

1. [obsidian-note-linker](https://github.com/AlexW00/obsidian-note-linker) - This is actively maintained and likely better suited for your needs.

2. If you're comfortable with Python and using Linux, you might be interested in what I'm currently using: [obsidian-plugin-python-bridge](https://github.com/mathe00/obsidian-plugin-python-bridge). While I'm not actively developing it either (mainly due to lack of contributors despite open requests for help, and my limited TypeScript/JavaScript expertise - I actually built the TS/JS bridge part using AI like ChatGPT), it allows you to create custom Python scripts to handle note linking (and other automations) in just a few lines of code. The repo is well-documented, especially regarding installation, and while it's Linux-only, it works well for implementing features I need. I personally use it with a custom Python script that handles automatic linking much more effectively than this plugin did.

To give you some context: this auto-linker was a brief project that lasted a few days before I decided to create the Python bridge instead. This way, I can quickly write simple Python plugins/scripts for each of my plugin ideas rather than developing them one by one in JS/TS, which I find quite challenging.

Feel free to let me know if you have any other questions!

**Comment by Nextovoy** [comment]
Hi @mathe00,

I'm very sad to hear that you are no longer supporting the plugin.

At the moment, I am already using the obsidian-note-linker plugin, but I don't like it. I have been looking for alternative solutions, and that's why I'm here. I am familiar with Python, but not well enough (to my deep regret). As for JS, I would prefer to never deal with it for personal reasons. 

Thank you for your response!

**Comment by mathe00** [comment]
> > I installed the plugin, but I didn't notice any new features - how does it work?
> > Could you provide a demo video or screenshots with a description? In other words, I need instructions on how to use the plugin.
> 
> Hi @Nextovoy,
> 
> Thank you for your interest in the plugin! I should mention that this was primarily a personal side project that I'm no longer actively maintaining.
> 
> Instead, I'd recommend checking out these alternatives:
> 
> 1. [obsidian-note-linker](https://github.com/AlexW00/obsidian-note-linker) - This is actively maintained and likely better suited for your needs.
> 2. If you're comfortable with Python and using Linux, you might be interested in what I'm currently using: [obsidian-plugin-python-bridge](https://github.com/mathe00/obsidian-plugin-python-bridge). While I'm not actively developing it either (mainly due to lack of contributors despite open requests for help, and my limited TypeScript/JavaScript expertise - I actually built the TS/JS bridge part using AI like ChatGPT), it allows you to create custom Python scripts to handle note linking (and other automations) in just a few lines of code. The repo is well-documented, especially regarding installation, and while it's Linux-only, it works well for implementing features I need. I personally use it with a custom Python script that handles automatic linking much more effectively than this plugin did.
> 
> To give you some context: this auto-linker was a brief project that lasted a few days before I decided to create the Python bridge instead. This way, I can quickly write simple Python plugins/scripts for each of my plugin ideas rather than developing them one by one in JS/TS, which I find quite challenging.
> 
> Feel free to let me know if you have any other questions!

Hi @Nextovoy,

I'm really sorry to hear that you're not satisfied with obsidian-note-linker. I totally understand - different tools work for different people! 

Since you mentioned you know some Python, I'd actually love to share with you the autolinker script I'm currently using. It's a simple but effective Python script that works with the obsidian-python-bridge plugin. I just had it translated to English to make it more accessible, and here it is:

```python
import sys
import os
import re
import unicodedata  # For handling accent removal

# Path to your library
library_path = "/home/YOURUSERNAMEFOREXAMPLE/Documents/Obsidian/SecondBrain/.obsidian/plugins/obsidian-python-bridge/"
sys.path.append(library_path)

from ObsidianPluginDevPythonToJS import ObsidianPluginDevPythonToJS

# Socket path
socket_path = "/tmp/obsidian-python-secondbrain.sock"
obsidian = ObsidianPluginDevPythonToJS(socket_path=socket_path)

# Configuration options
preserve_case_option = True
match_plural_option = True
ignore_accents_option = True

# Function to get all note titles
def get_all_note_titles():
    return obsidian.get_all_note_titles()

# Function to normalize a string by removing accents
def remove_accents(text):
    return ''.join(
        c for c in unicodedata.normalize('NFD', text)
        if unicodedata.category(c) != 'Mn'
    )

# Function to transform text into a wikilink while preserving case
def create_wikilink(original_text, title):
    if preserve_case_option:
        return f'[[{title}|{original_text}]]'
    else:
        return f'[[{title}|{title}]]'

# Function to check if a word is already in a link
def is_inside_link(index, content):
    link_start = content.rfind("[[", 0, index)
    link_end = content.find("]]", index)
    return link_start != -1 and link_end != -1 and link_start < index < link_end

# Main function to create wikilinks with multiple iterations on each line
def create_wikilinks(content, titles):
    # Sort titles by descending length to prioritize longer matches
    titles = sorted(titles, key=len, reverse=True)
    total_links_created = 0
    lines = content.splitlines()

    # Normalize titles for accent removal if the option is enabled
    normalized_titles = [remove_accents(title) if ignore_accents_option else title for title in titles]

    for line_index, line in enumerate(lines):
        # Ignore lines that start with one or more #
        if line.lstrip().startswith("#"):
            continue  # Skip this line as it's a Markdown heading

        line_modified = True
        while line_modified:  # Continue processing the line until no more matches are found
            line_modified = False
            for title, normalized_title in zip(titles, normalized_titles):
                # Adjust regex to consider apostrophes as separators
                regex = re.compile(rf"(?<!\w)'?\b{re.escape(normalized_title)}\b(?!\w)", re.IGNORECASE)

                def replace_match(match):
                    nonlocal line_modified
                    if not is_inside_link(match.start(), line):
                        original_text = match.group(0)
                        line_modified = True  # Mark that the line has been modified
                        return create_wikilink(original_text, title)
                    return match.group(0)

                # Perform substitution on the line
                new_line, num_subs = regex.subn(replace_match, line)
                if num_subs > 0:
                    line = new_line  # Update the line
                    total_links_created += num_subs
                    obsidian.show_notification(f"{num_subs} wikilink(s) created for title: {title} on line {line_index + 1}")

        # Update content with the modified line
        lines[line_index] = line

    # Join all modified lines to recreate the global content
    return "\n".join(lines), total_links_created

# Function to properly handle frontmatter (preserve frontmatter and process the rest of the content)
def split_frontmatter(content):
    lines = content.splitlines()
    frontmatter = []
    body = []
    dash_count = 0
    is_frontmatter = False

    # Identify if there's frontmatter and process lines accordingly
    for line in lines:
        if line.strip() == "---":
            dash_count += 1
            if dash_count == 1:
                is_frontmatter = True
            elif dash_count == 2 and is_frontmatter:
                frontmatter.append(line)
                is_frontmatter = False
                continue

        if is_frontmatter:
            frontmatter.append(line)
        else:
            body.append(line)

    return "\n".join(frontmatter), "\n".join(body)

# Main function
def main():
    obsidian.show_notification("Starting wikilinks creation script...")

    titles = obsidian.get_all_note_titles()
    note_path = obsidian.get_active_note_absolute_path()

    # Read file content
    try:
        with open(note_path, 'r', encoding='utf-8') as file:
            content = file.read()
    except Exception as e:
        obsidian.show_notification(f"Reading error: {str(e)}")
        return

    # Split frontmatter and content
    frontmatter, content_to_process = split_frontmatter(content)

    # Add wikilinks in the main content
    updated_content, total_links_created = create_wikilinks(content_to_process, titles)

    # Reintegrate frontmatter with updated content
    if frontmatter.strip():
        final_content = f"{frontmatter}\n{updated_content}"
    else:
        final_content = updated_content

    # Save modifications to file
    try:
        with open(note_path, 'w', encoding='utf-8') as file:
            file.write(final_content)
        obsidian.show_notification(f"Script completed: {total_links_created} wikilinks added.")
    except Exception as e:
        obsidian.show_notification(f"Save error: {str(e)}")

# Execute the script
if __name__ == "__main__":
    main()
```

The script automatically creates wikilinks in your notes by matching text with your existing note titles. It handles things like case preservation, accents, and frontmatter, and you can easily customize it to your needs since it's all in Python.

If you're interested, I can help you get started with it. All you'd need is the obsidian-python-bridge plugin installed, and I can guide you through the setup.

Let me know if you'd like to give it a try! 😊

**Comment by Nextovoy** [comment]
Wow, thanks! 

But... It seems I have found the holy grail that still works to this day: https://forum.obsidian.md/t/new-plugin-link-with-alias-fast-link-creation-including-link-alias/62330

I didn't expect to find something like this, but it does exactly what I wanted – it keeps the alias in the text, adding an alias with the given pseudonym to the target note. I've been using Obsidian for a whole year, but just a few days ago the thought crossed my mind to create my own knowledge base (yes, you could say I've joined a cult where people are obsessed with creating the perfect knowledge base), similar to a Wiki. And now I'm at the stage of creating a kind of test environment in a separate vault to understand what I want to see in the notes and what needs to be done to bring the notes to a certain format. In fact, only 5 days have passed – in these days I've learned a lot. It's a pity that such a popular tool as note linking is ridiculously inconvenient to use.

Your work on creating plugins in Python is impressive; I'm glad there are people who enjoy doing such things.

**Comment by mathe00** [comment]
> Wow, thanks!
> 
> But... It seems I have found the holy grail that still works to this day: https://forum.obsidian.md/t/new-plugin-link-with-alias-fast-link-creation-including-link-alias/62330
> 
> I didn't expect to find something like this, but it does exactly what I wanted – it keeps the alias in the text, adding an alias with the given pseudonym to the target note. I've been using Obsidian for a whole year, but just a few days ago the thought crossed my mind to create my own knowledge base (yes, you could say I've joined a cult where people are obsessed with creating the perfect knowledge base), similar to a Wiki. And now I'm at the stage of creating a kind of test environment in a separate vault to understand what I want to see in the notes and what needs to be done to bring the notes to a certain format. In fact, only 5 days have passed – in these days I've learned a lot. It's a pity that such a popular tool as note linking is ridiculously inconvenient to use.
> 
> Your work on creating plugins in Python is impressive; I'm glad there are people who enjoy doing such things.

Cool find! I actually did extensive research before developing my plugins but somehow missed this one. It's a great tool for what it does - making manual link creation more ergonomic, which is honestly one of Obsidian's pain points. The default wiki-style linking in Obsidian can be quite cumbersome, and I totally understand how that frustration led you (and me!) to look for better solutions.

Your use case and mine seem slightly different though. While this plugin helps with manual link creation, what I was looking for (and what I created) was automatic link creation. For example, if you have a note that says:

"I'm a fan of cats and it's a mammal."

And you have notes in your vault called "Cats" and "Mammals", the script automatically transforms it into:

"I'm a fan of [[Cats|cats]] and it's a [[Mammals|mammal]]."

This automation was the main driver behind my development efforts - wanted the system to do the heavy lifting for us! 

And I love how you're diving deep into creating your perfect knowledge base! It's super exciting to see another person getting into the Obsidian ecosystem, especially for Second Brain and Zettelkasten approaches. The way this tool pulls you in and makes you want to optimize everything is exactly what happened to me too. The community's passion for continuous improvement is what makes Obsidian really special.

Keep exploring and have fun with your setup! Whether you go with this plugin, my script, or both - that's the magic of Obsidian right there. Always happy to chat about PKM stuff! 😊
